### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by id-clic** [wahyubucil/adonis-mix-asset#6]
## Description

Hi !

When I execute the command "node ace mix:watch", I have an error :

TypeError: The "path" argument must be of type string. Received undefined

1 MixWatch.run
  /Users/steve/Sites/Labo/file-manager/node_modules/adonis-mix-asset/build/commands/Mix/Watch.js:20

2 Injector.callAsync
  /Users/steve/Sites/Labo/file-manager/node_modules/@adonisjs/fold/build/src/Ioc/Injector.js:124

## Package version
2.3.0

**Comment by dawidow** [comment]
@id-clic hey bro, can you paste here what do you have inside your `webpack.mix.js` file? Can you send us your configuration files?

**Comment by wahyubucil** [comment]
Hi @id-clic, can you try to use the new v3.0.0? I've already made it compatible with the latest AdonisJS release. If it does solve your problem, feel free to close this issue. Thanks!
